apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: karate-executor
  namespace: testkube
spec:
  executor_type: job
  # image: lreimer/testkube-karate-executor:main
  image: ghcr.io/lreimer/testkube-executor-karate:main
  types:
  - karate/feature
  - karate/project
  features:
    - artifacts