name: Code build and checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Setup JBang
        run: make install-jbang

      - name: Setup Karate
        run: make install-karate

      - name: Test
        run: go test -v ./...
